### ISSUE TITLE
Incompatible with SD 3.5.x/Chameleon 2.2.x

### ISSUE THREAD

**Issue by Belgabor** [Belgabor/DrawersBits#8]
*le sigh*

**Comment by jaquadro** [comment]
Sorry, just discovered that fact now and was going to open a PR for you.  You'll need to override the method overridesShouldSideBeRendered to return false (or re-implement shouldSideBeRendered without calling to super, which would mean copying a bunch of code from Block).

**Comment by jaquadro** [comment]
I've put in a fix to 3.5.4 that will avoid crashing with existing versions of D&B.  The PR I submitted will just bypass the exception handling.

**Comment by Belgabor** [comment]
Awesome! What issues are you trying to combat?

**Comment by jaquadro** [comment]
Well... same reason I'm about to put out 3.5.5 (because I didn't hit all the cases in 3.5.4).

The base drawers class has the BLOCK property for the various sizes, but compacting drawers (and DB drawers) specifically exclude that property, which means ever referencing it is a chance things will break.  Standard drawers should belong to their own subclass and BLOCK taken out of the base entirely.

**Comment by Belgabor** [comment]
Ah I see. Well, it works with 3.5.5 but there is still a bug getting things out of the compacting drawer so I'll keep this issue open until I fix that.

**Comment by Belgabor** [comment]
The issue is apparently a forge issue and is present with the vanilla drawers as well. Closing this.
